// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utybcigdveyqlkjckgzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0eWJjaWdkdmV5cWxramNrZ3pxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyOTc5OTIsImV4cCI6MjA3MTg3Mzk5Mn0.dmdo2uyMYvFc0zIXp35Ip74QBB3Uw4UkbhbXSRVPZCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});